---
title: "Shiny, Slack, AWS, Sql, and Auto-Cleaning"
author: "Avi + Joe"
date: "October 15, 2015"
output: html_document
---

##First we set off to build an automated data cleaning system

To get the mysql data into the AMi
```{r}
curl -0 http://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.0.8.tar.gz | tar -zx

``

Part of the reason R is awful:
There are many modeling packages written by different people, and there are regular inconsistencies in how models are specified and predictions are made. 

obj	Class 	Package 	predict Function Syntax
lda		 	MASS 	predict(obj) (no options needed)
glm 		stats 	predict(obj, type = "response")
gbm		 	gbm 	predict(obj, type = "response", n.trees)
made	 	mda 	predict(obj, type = "posterior")
rpart 		rpart 	predict(obj, type = "prob")
Weka 		RWeka 	predict(obj, type = "probability")
LogitBoost caTools 	predict(obj, type = "raw", nIter)

##Then we found Dataiku

```{r}
```

##Then we set out to automate the process of cleaning data and building models

##Then we found Caret

##Then we put it all together